# Generated by Django 2.0.9 on 2020-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('availability', models.CharField(choices=[('STANDARD', 'Standard Pool'), ('SPECIAL', 'Limited Hero'), ('GHB', 'Grand Hero Battle'), ('TT', 'Tempest Trials'), ('LEGENDARY', 'Legendary Hero'), ('MYTHIC', 'Mythic Hero'), ('STORY', 'Story Hero')], max_length=15)),
                ('is_f2p', models.BooleanField()),
                ('movement_type', models.CharField(choices=[('INFANTRY', 'Infantry'), ('ARMOR', 'Armor'), ('FLYING', 'Flying'), ('CAVALRY', 'Cavalry')], max_length=15)),
                ('weapon_type', models.CharField(choices=[('SWORD', 'Sword'), ('LANCE', 'Lance'), ('AXE', 'Axe'), ('R_TOME', 'Red Tome'), ('B_TOME', 'Blue Tome'), ('G_TOME', 'Green Tome'), ('C_TOME', 'Colorless Tome'), ('R_BOW', 'Red Bow'), ('B_BOW', 'Blue Bow'), ('G_BOW', 'Green Bow'), ('C_BOW', 'Colorless Bow'), ('R_DAGGER', 'Red Dagger'), ('B_DAGGER', 'Blue Dagger'), ('G_DAGGER', 'Green Dagger'), ('C_DAGGER', 'Colorless Dagger'), ('R_DRAGON', 'Red Dragonstone'), ('B_DRAGON', 'Blue Dragonstone'), ('G_DRAGON', 'Green Dragonstone'), ('C_DRAGON', 'Colorless Dragonstone'), ('R_BEAST', 'Red Beast'), ('B_BEAST', 'Blue Beast'), ('G_BEAST', 'Green Beast'), ('C_BEAST', 'Colorless Beast'), ('C_STAFF', 'Staff')], max_length=15)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('COLORLESS', 'Colorless')], max_length=15)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('resistance', models.IntegerField()),
                ('bst', models.IntegerField()),
                ('pullable_3star', models.BooleanField()),
                ('pullable_4star', models.BooleanField()),
                ('pullable_5star', models.BooleanField()),
            ],
        ),
    ]
