# Generated by Django 2.0.9 on 2020-03-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0002_auto_20200315_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='movement_type',
            field=models.CharField(choices=[('INFANTRY', 'Infantry'), ('ARMOR', 'Armor'), ('FLYING', 'Flying'), ('CAVALRY', 'Cavalry')], max_length=15, verbose_name='move'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weapon_type',
            field=models.CharField(choices=[('SWORD', 'R Sword'), ('LANCE', 'B Lance'), ('AXE', 'G Axe'), ('R_TOME', 'R Tome'), ('B_TOME', 'B Tome'), ('G_TOME', 'G Tome'), ('C_TOME', 'C Tome'), ('R_BOW', 'R Bow'), ('B_BOW', 'B Bow'), ('G_BOW', 'G Bow'), ('C_BOW', 'C Bow'), ('R_DAGGER', 'R Dagger'), ('B_DAGGER', 'B Dagger'), ('G_DAGGER', 'G Dagger'), ('C_DAGGER', 'C Dagger'), ('R_DRAGON', 'R Dragon'), ('B_DRAGON', 'B Dragon'), ('G_DRAGON', 'G Dragon'), ('C_DRAGON', 'C Dragon'), ('R_BEAST', 'R Beast'), ('B_BEAST', 'B Beast'), ('G_BEAST', 'G Beast'), ('C_BEAST', 'C Beast'), ('C_STAFF', 'C Staff')], max_length=15, verbose_name='weapon'),
        ),
    ]
