# Generated by Django 2.0.9 on 2020-03-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0004_auto_20200322_0737_squashed_0005_auto_20200322_0737_squashed_0005_auto_20200322_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='gamepedia_url',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
