# Generated by Django 2.2.10 on 2020-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feh', '0006_auto_20200322_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='availability',
            field=models.CharField(choices=[('STANDARD', 'Standard Pool'), ('SPECIAL', 'Limited Hero'), ('GHB', 'Grand Hero Battle'), ('TT', 'Tempest Trials'), ('LEGENDARY', 'Legendary Hero'), ('MYTHIC', 'Mythic Hero'), ('STORY', 'Story Hero'), ('DUO', 'Duo Hero')], max_length=15),
        ),
    ]
